### ISSUE TITLE
[Bug 0.37.2 Pivot Table] Pivot table not work correctly with Sum Total - Version 0.37.2

### ISSUE THREAD

**Issue by justinphamvn** [apache/incubator-superset#11298]
Pivot table not work correctly with **Sum Total**
I have a Pivot Table with:

Distributor Code / Sum of Quantity / Sum of Amount
2000006 / 31,637 / 468,966,500
2000013 / 28,826 / 238,210,000
 
### Expected results
**Sum Total work correctly**
Total Quantity: **60,463**
Total Amount: **707,176,500**

### Actual results
**Sum Total not work correctly** 
Total Quantity: **31,637** (_It's only calculate with MAX instead SUM function_)
Total Amount: **468,966,000** ( _Max and Auto Rounding !!!_ )

#### Screenshots

![Superset_PivotTable_issues](https://user-images.githubusercontent.com/72958231/96210995-5842ff80-0f9d-11eb-9175-4c722abe9b66.png)

### Environment

- superset version: 0.37.2
- python version: 3.6

**Comment by junlincc** [comment]
thanks for reporting @justinphamvn justinphamvn

It looks like there are more issues around the pivot table besides sorting and icons...... 

https://github.com/apache/incubator-superset/issues/11268
https://github.com/apache/incubator-superset/issues/11250
https://github.com/apache/incubator-superset/issues/10737 

@villebro

**Comment by villebro** [comment]
@justinphamvn are you sure your columns are numeric? This is what I'm getting on current master (I didn't test on 0.37.2, but I suspect the behavior to be the same):
![image](https://user-images.githubusercontent.com/33317356/96221842-e74b1a00-0f93-11eb-9b1a-e967359636cc.png)

**Comment by justinphamvn** [comment]
> @justinphamvn are you sure your columns are numeric? This is what I'm getting on current master (I didn't test on 0.37.2, but I suspect the behavior to be the same):
> ![image](https://user-images.githubusercontent.com/33317356/96221842-e74b1a00-0f93-11eb-9b1a-e967359636cc.png)

Hi @villebro 
Yes, it is definitely a numeric type because before upgrade to 0.37.2 It work very well on 0.37.0 version

![Superset_PivotTable](https://user-images.githubusercontent.com/72958231/96224057-25a70000-0fb9-11eb-80d4-1a48031b0c37.png)

**Comment by junlincc** [comment]
@justinphamvn this issue should have been fixed in master, can you double check? thanks !

**Comment by ktmud** [comment]
This bug still exists:

Here's a test query to reproduce:

```sql
SELECT 1 as metric1, 2 as metric2, 'a' as dim1, 'a' as dim2
UNION SELECT 2, 0, 'b', 'a'
UNION SELECT 5, 2, 'a', 'a'
UNION SELECT null, 5, 'c', 'b'
```

Create a virtual datasource using this query, use both `metric1` and `metric2` in metrics, and select `dim1` in "Group by"

**Comment by ktmud** [comment]
<img src="https://user-images.githubusercontent.com/335541/98973043-16d44000-24c8-11eb-9c29-86892d2c6e3e.png" width="300">

As you can see, the sum for `sum(metric2)` is incorrect. It ignores the last row `dim1 = c` where `sum(metric1)` is null.

**Comment by magic-overflow** [comment]
![image](https://user-images.githubusercontent.com/7246515/101345420-941d8580-38b9-11eb-803f-3e1dcfbb27c8.png)
Version 0.38.0

**Comment by korridor** [comment]
I am also still having the same problem with version 0.38.0.

**Comment by ErinYener** [comment]
I am having this same issue on version 0.37.2; any updates would be appreciated!

**Comment by korridor** [comment]
I think somebody else (@kakoni) created an issue for the same problem here: #11658

**Comment by djouallah** [comment]
I have the same problem, the total of division is wrong
![image](https://user-images.githubusercontent.com/12554469/135704367-e7df4555-e445-4fa0-a028-5140dc7562f6.png)

**Comment by EikotheRookie** [comment]
> I have the same problem, the total of division is wrong ![image](https://user-images.githubusercontent.com/12554469/135704367-e7df4555-e445-4fa0-a028-5140dc7562f6.png)

I have the same problem too.The subtotal is also wrong.

**Comment by EikotheRookie** [comment]
I have the same problem, the subtotal and the total of division is wrong.

![superset_issue](https://user-images.githubusercontent.com/19757515/141055357-7a9a9a8b-ca26-4ed9-8370-82a80eabe56c.png)

**Comment by EikotheRookie** [comment]
I have the same problem, the subtotal and the total of division is wrong.
I'm using Pivot Table v2 under apache-superset version 1.3.2.

![superset_issue](https://user-images.githubusercontent.com/19757515/141055696-6af08b4d-773e-4314-bff4-116aa88555d6.png)

**Comment by rumbin** [comment]
In my understanding, the `progress` column, which ist the division of the previous two columns, is a SQL metric rather than a post-processed value?!
In that case, Superset cannot know about the fact that this is a division and how to correctly summarize this metric.
There is no way to correctly summarize just this `progress` column alone.

Or am I misunderstanding the problem?

**Comment by EikotheRookie** [comment]
Yes,you got it. 

In TABLE VIZ we can get a correct  (total of actural)/ (total of buget). But there is no way to add  (sutotal of actural)/ (total of buget) for each group.
![superset_issue_2](https://user-images.githubusercontent.com/19757515/141926960-d2829012-712b-4723-82d5-25eb4db0c6db.png)

In Pivot Table v2 , I can show both the Subtotal and Total row as i wish. But the result of (total of actural)/ (total of buget) and (subtotal of actural)/ (subtotal of buget) is a wrong number.

So Is there anyway to calculate a right divison of (total of actural)/ (total of buget)?

**Comment by jgarcia-74** [comment]
Is there a way we could specify the aggregtion function per column, instead of using the same aggregation across the different metrics?  I have a combination of columns which are sales and margins, for examples.  So, I would like to use the sum aggregation for the sales metrics and the average aggregation for the margins.  (Now, this wouldn't solve the issue that was discribed, where the total sales/total cost would be needed to get the accurate percentage).  Is there a way to do this?  I was able to modify the regular table chart, to include the hierarchy drilling, and the ability to specify the aggregation by column, however, there are some features from the pivottable that we would like to use.  How difficult would this be to accomplish?
