### ISSUE TITLE
Timeseries tooltips (on dashboard) not working on FF

### ISSUE THREAD

**Issue by DaimonPl** [apache/incubator-superset#1364]
As in title, firefox does not display tooltips on time series when slice is used on dashboard. When slice is explored it works fine

Chrome displays tooltip in same scenario.

(0.11)

**Comment by xrmx** [comment]
Is there any error on the console?

**Comment by DaimonPl** [comment]
Nope, developer console is clear. Tooltips are working for parts like "explore" icon, but for timeseries itself nothing displays (in this case I'm using time series with time shift - not sure if it matters)

FF 49

**Comment by rumbin** [comment]
Confirming this issue for Firefox 45.4.0.
I'm using Vivaldi browser as a workaround; however, FF-support is crucial in my eyes...

**Comment by rumbin** [comment]
FF 51.0.1 64 Bit shows the same behavior.

**Comment by xrmx** [comment]
@rumbin  Everyone has its own priorities, if it's crucial then please go fix it :)

**Comment by rumbin** [comment]
@xrmx I would, if I could. However, I guess that it's a js issue and this is far beyond my skills which consist of a tiny bit of python.

**Comment by RichRadics** [comment]
FF 51.0.1 OSX 10.12 - the tooltips /do/ work on a dashboard, but they're functioning relative to the top left of the workspace. i.e. if the chart is positioned in the top left corner, everything looks fine - move it down and to the right, and the tooltips only appear when a) the cursor is over the chart, and b) the cursor is in the area that the chart would occupy if it was in the top left corner.

**Comment by pajachiet** [comment]
Thanks for your analysis @RichRadics 

We still have this issue with recent version of Superset 0.18.5. How do you update nvd3 to latest version in Superset ?

**Comment by pajachiet** [comment]
Thanks for your analysis @RichRadics 

We still have this issue with recent version of Superset 0.18.5. How do you update nvd3 to latest version in Superset ?

**Comment by RichRadics** [comment]
This was committed into superset in PR #3378 so should be fixed in the next release

**Comment by xrmx** [comment]
@DaimonPl please close the issue, thanks!

**Comment by DaimonPl** [comment]
I just checked this problem on Superset 0.19.1 and it still exists on Firefox

**Comment by pajachiet** [comment]
I confirm. I also checked with Superset 0.19.1 and it still exists on Firefox.

**Comment by xrmx** [comment]
@DaimonPl the commit has been applied *after* 0.19.1 so test master or close the issue please.

@pajachiet no need for me too comments please.

**Comment by DaimonPl** [comment]
Verified it's working fine with 0.20.0

**Comment by MahsaSeifikar** [comment]
I've recently built a dashboard on Superset 0.35.1 and this issue still exists on Firefox. How can I fix that?
