### ISSUE TITLE
hive error  : 'TSaslClientTransport' object has no attribute 'readAll'

### ISSUE THREAD

**Issue by flofei** [apache/incubator-superset#3451]
I am having trouble getting SuperSet to connect to hive using the web interface. I go to add a database (using the URI that works in DBVis). My connection string is set as such: hive://user:password@iport/?auth=LDAP. When I test the connection I receive the following error: TSaslClientTransport' object has no attribute 'readAll'

### Superset version
superset 0.19.0

### Expected results
 test is ok

### Actual results

   (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "/usr/local/python3.5/bin/venv/lib/python3.5/site-packages/thrift/protocol/TBinaryProtocol.py", line 134, in readMessageBegin
    sz = self.readI32()
  File "/usr/local/python3.5/bin/venv/lib/python3.5/site-packages/thrift/protocol/TBinaryProtocol.py", line 217, in readI32
    buff = self.trans.readAll(4)
AttributeError: 'TSaslClientTransport' object has no attribute 'readAll'

### Steps to reproduce

pip install thrift==0.9.3
pip install pyhive[hive]
pip install git+https://github.com/cloudera/thrift_sasl

**Comment by xrmx** [comment]
Looks very much unrelated to superset but pretty difficult to sort out without a full stackstrace. Please post the full one and quote in markdown properly.

**Comment by flofei** [comment]
full stacktace belows: 
```
Traceback (most recent call last):
  File "/usr/local/python3.5/bin/venv/lib/python3.5/site-packages/superset-0.19.0-py3.5.egg/superset/views/core.py", line 1459, in testconn
    engine.connect()
  File "/usr/local/python3.5/bin/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2091, in connect
    return self._connection_cls(self, **kwargs)
  File "/usr/local/python3.5/bin/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 90, in __init__
    if connection is not None else engine.raw_connection()
  File "/usr/local/python3.5/bin/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2177, in raw_connection
    self.pool.unique_connection, _connection)
  File "/usr/local/python3.5/bin/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2147, in _wrap_pool_connect
    return fn()
  File "/usr/local/python3.5/bin/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 328, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/local/python3.5/bin/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/python3.5/bin/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/usr/local/python3.5/bin/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 1138, in _do_get
    self._dec_overflow()
  File "/usr/local/python3.5/bin/venv/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/python3.5/bin/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/python3.5/bin/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 1135, in _do_get
    return self._create_connection()
  File "/usr/local/python3.5/bin/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
 File "/usr/local/python3.5/bin/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/python3.5/bin/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/python3.5/bin/venv/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/python3.5/bin/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/python3.5/bin/venv/lib/python3.5/site-packages/pyhive/hive.py", line 64, in connect
    return Connection(*args, **kwargs)
  File "/usr/local/python3.5/bin/venv/lib/python3.5/site-packages/pyhive/hive.py", line 164, in __init__
    response = self._client.OpenSession(open_session_req)
  File "/usr/local/python3.5/bin/venv/lib/python3.5/site-packages/TCLIService/TCLIService.py", line 187, in OpenSession
    return self.recv_OpenSession()
  File "/usr/local/python3.5/bin/venv/lib/python3.5/site-packages/TCLIService/TCLIService.py", line 199, in recv_OpenSession
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "/usr/local/python3.5/bin/venv/lib/python3.5/site-packages/thrift/protocol/TBinaryProtocol.py", line 134, in readMessageBegin
    sz = self.readI32()
  File "/usr/local/python3.5/bin/venv/lib/python3.5/site-packages/thrift/protocol/TBinaryProtocol.py", line 217, in readI32
    buff = self.trans.readAll(4)
AttributeError: 'TSaslClientTransport' object has no attribute readAll
```

**Comment by flofei** [comment]
this problem is not related to superset. the thrift-sasl is wrong.i fixed.

**Comment by beenhead** [comment]
As a bit of an expansion on this, I found that upgrading my thirft-sasl was the fix:

`pip install thrift-sasl --upgrade`

**Comment by tarekabouzeid** [comment]
i executed "pip install thrift-sasl --upgrade" , but i still facing same issue, have you managed to solve it?

**Comment by tarekabouzeid** [comment]
Name: thrift-sasl
Version: 0.3.0

Name: thrift
Version: 0.11.0

Name: sasl
Version: 0.2.1
