### ISSUE TITLE
database_access on [mydb] permissionview not created when database added

### ISSUE THREAD

**Issue by andrewsali** [apache/incubator-superset#4398]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.22.1

### Expected results
When a new database is added, immediately afterwards the permissionview `database_access on [mydb]` should be created.

### Actual results
Permissionview is not created (only schema permissionviews and datasource permissionviews are created). If an update is run on the db, then the `database_access` permissionview is created.

### Steps to reproduce
Add a new database and without any further actions try creating a role that has `database_access` on this database. This is not possible as permissionview does not exist. If an update is run on the database (without changing anything) then permissionview is correctly created.

Looking at the code it appears that in this line it should use `db.get_perm()` instead `db.perm` as `db.perm` is not set before the database is inserted (it is only set after insert).

https://github.com/apache/incubator-superset/blob/2e172d77cf87ef9b4850f5fa183a2b1815bb6e58/superset/views/core.py#L263

**Comment by andrewsali** [comment]
Unfortunately changing to `get_perm()` doesn't solve the issue as before insert the database has no pk value yet.

So probably having a seperate `set_perm` behaviour for databases would be needed (as this is executed after insert), that also adds `database_access` permission and not just `datasource`.

**Comment by andrewsali** [comment]
The following resolves this issue:

https://github.com/andrewsali/incubator-superset/commit/00e9820934e47dc1c67f53aa1facf5bab976ecb0

**Comment by mistercrunch** [comment]
@andrewsali thank you for digging in, please open a PR!

**Comment by qin4zhang** [comment]
Resolved? Which version?

**Comment by mistercrunch** [comment]
Not resolved, someone needs to submit a PR with the changes above.
