### ISSUE TITLE
Data too long for column 'type' at row 1

### ISSUE THREAD

**Issue by ghost** [apache/incubator-superset#5018]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25.2

Configuration : 
OS: Ubuntu 18.04 LTS
Python: 3.6,
Backend Source database : MS SQL Server
Metadatabase : mysql

Trying to refresh Column Metadata of a table, I'm getting the following error : 
(Similar issue : #4271)

Exception on /tablemodelview/action_post [POST]
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.DataError: (1406, "Data too long for column 'type' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/flask_appbuilder/views.py", line 578, in action_post
    return action.func(items)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/superset/connectors/sqla/views.py", line 300, in refresh
    t.fetch_metadata()
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/superset/connectors/sqla/models.py", line 793, in fetch_metadata
    self.add_missing_metrics(metrics)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/superset/connectors/base/models.py", line 127, in add_missing_metrics
    exisiting_metrics = {m.metric_name for m in self.metrics}
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 242, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 599, in get
    value = self.callable_(state, passive)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 623, in _load_for_state
    return self._emit_lazyload(session, state, ident_key, passive)
  File "<string>", line 1, in <lambda>
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 747, in _emit_lazyload
    result = q(session).params(**params).all()
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/ext/baked.py", line 434, in all
    return list(self)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/ext/baked.py", line 336, in __iter__
    self.session._autoflush()
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1444, in _autoflush
    util.raise_from_cause(e)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1434, in _autoflush
    self.flush()
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2243, in flush
    self._flush(objects)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2369, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2333, in _flush
    flush_context.execute()
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 866, in _emit_insert_statements
    execute(statement, params)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/home/user/anaconda3/envs/super/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.DataError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (_mysql_exceptions.DataError) (1406, "Data too long for column 'type' at row 1") [SQL: 'INSERT INTO table_columns (created_on, changed_on, column_name, verbose_name, is_active, type, groupby, count_distinct, sum, avg, max, min, filterable, description, table_id, is_dttm, expression, python_date_format, database_expression, created_by_fk, changed_by_fk) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (datetime.datetime(2018, 5, 16, 20, 37, 19, 347918), datetime.datetime(2018, 5, 16, 20, 37, 19, 347923), 'RES_KEY', None, 1, 'NVARCHAR(255) COLLATE GREEK_CI_AS', 1, 0, 0, 0, 0, 0, 1, None, 13, 0, '', None, None, 1, 1)] (Background on this error at: http://sqlalche.me/e/9h9h)

**Comment by mts2016** [comment]
Fixed by : 

mysql> ALTER TABLE table_columns MODIFY type varchar(255);

( Extra post-install overhead, please consider incorporate it in the next release ...)

**Comment by nileio** [comment]
hi all , this issue still exists in the latest release..
Using mysql 8 as the backend database.. mysql 8 seem to have long names for field types such as VARCHAR (32) CHARACTERSET_XYZMB4 which exceed the 32 varchar field limit you use for column 'type' of table_columns table .. could you please consider making this change ? I also executed ALTER TABLE and changed the size of this column

**Comment by nileio** [comment]
@craig-rueda further to this issue , I also can confirm that this issue affects other function too.. When editing any column with a long type such as "VARCHAR(128) CHARACTER SET UTF8MB4" .. it does not save the update for that column. If I change to reduce the length of the field, say change that to "VARCHAR(128)" and get rid of the rest then the column update is saved successfully..
it looks like there are other fields somewhere in the meta database that needs to adjust the size..
please note.

thanks

**Comment by villebro** [comment]
Thanks @nileio . Currently Superset filters out collation info from column types, but not character set info. I will look into fixing this.
