### ISSUE TITLE
How to modify the order of the Pivot Table

### ISSUE THREAD

**Issue by Sdzspz** [apache/incubator-superset#6137]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.27.0

### Expected results
![image](https://user-images.githubusercontent.com/32638556/47138936-3c90ba00-d2ed-11e8-8dad-d9cb69fd7754.png)

![image](https://user-images.githubusercontent.com/32638556/47139827-57fcc480-d2ef-11e8-8360-1b0a836eeed2.png)

I use the Pivot Table to show the data.My sql is sorted correctly, but the Pivot Table sorting is different from sql.why?

**Comment by yamyamyuo** [comment]
this should be fixed in master https://github.com/apache/incubator-superset/pull/5566/commits/527e398b32546ccd20ebc02b466b76f36a411fbc

**Comment by Sdzspz** [comment]
I tried to use 0.28.0 and 0.28.1, but this problem still exists in the new version

**Comment by yamyamyuo** [comment]
interesting, https://github.com/apache/incubator-superset/blob/48b7ebea1346820ec68e8c8ae8b3d70c81fc5281/superset/viz.py#L99 this should have fixed. check if `Pivot Table` is inherit from `class BaseViz ` and use this `process_metrics` function to generate the metrics order.

**Comment by Neel-rishabhsoft** [comment]
@yamyamyuo This issue is in the latest version of superset as well. Not sure where to call this function in pivot table viz function. Can you please tell me that? I have checked that base viz has the process_metric function and pivot table is inheriting it.
