### ISSUE TITLE
Deck.gl onHover Tooltip does not show anymore 

### ISSUE THREAD

**Issue by lucien-roquette** [apache/incubator-superset#6306]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28.1

### Expected results
Tooltip window showing the content onHover. 

### Actual results
Nothing appears, but this error in the Console 
```
Uncaught TypeError: r is not a function
    at Object.onHover (scatter.af46ba94611577f0cf94.chunk.js:formatted:276)
    at p-efe0b931.813efd350b3c9b7ba049.chunk.js:2
    at Map.forEach (<anonymous>)
    at p-efe0b931.813efd350b3c9b7ba049.chunk.js:2
    at Ge (p-efe0b931.813efd350b3c9b7ba049.chunk.js:2)
    at Ue (p-efe0b931.813efd350b3c9b7ba049.chunk.js:2)
    at e.value (p-efe0b931.813efd350b3c9b7ba049.chunk.js:2)
    at e.value (p-efe0b931.813efd350b3c9b7ba049.chunk.js:2)
    at Array.<anonymous> (p-39b91eb9.81565bc93ff56be4e334.chunk.js:2)
    at ee.emit (p-39b91eb9.81565bc93ff56be4e334.chunk.js:2)
```
### Steps to reproduce
Create a map and a function that returns a "test_string" in Javascript onClick href

**Comment by Bit-Doctor** [comment]
The incriminating bit seems to be: 
https://github.com/apache/incubator-superset/blob/48b7ebea1346820ec68e8c8ae8b3d70c81fc5281/superset/assets/src/visualizations/deckgl/layers/common.jsx#L49-L55
where `setTooltip` is not a function.

This worked fine on previous versions.

**Comment by mistercrunch** [comment]
Pretty sure this is fixed in `master`

**Comment by mistercrunch** [comment]
@lucien-roquette let me know if I need to re-open

**Comment by jaksmid** [comment]
@mistercrunch I am still having the issue, installed the latest version of superset from `pypi`.
