### ISSUE TITLE
Charts No Longer Render Visualizations

### ISSUE THREAD

**Issue by csc5k** [apache/incubator-superset#6416]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
28.0

### Expected results
When I create a chart, I should see some kind of visualization. I'm logged in as admin

### Actual results
I don't see anything. This broke all of my charts that I had built in v27.0
![image](https://user-images.githubusercontent.com/33062840/48772272-e7501b80-ec91-11e8-9d21-1e5808ea1bd3.png)

### Steps to reproduce
It seems like literally make any chart, any visualization style

**Comment by csc5k** [comment]
Similarly, if I write a query in SQL Lab, it returns results, and when I click Explore I am presented with a table:
![image](https://user-images.githubusercontent.com/33062840/48782031-3ce4f200-ecab-11e8-8e7a-a3dcf65d8c8c.png)

However, when I try to convert this to a Bar Chart (or seemingly any other viz type), I do not get any viz rendered:
![image](https://user-images.githubusercontent.com/33062840/48782083-63a32880-ecab-11e8-8ca6-35dd25c18dfa.png)

Although it does display that 3 rows were returned, and here are the values:
![image](https://user-images.githubusercontent.com/33062840/48782106-7289db00-ecab-11e8-8445-cc89d60cbe81.png)

**Comment by csc5k** [comment]
It works if I selected Partition Diagram and then moved it back to Bar Chart. Seems like a bug of some sort though

**Comment by kristw** [comment]
Does the browser console include any error message?

**Comment by kristw** [comment]
This should be fixed in recent version. Please reopen if persists.

**Comment by samlrichards** [comment]
I'm still experiencing this while using the latest version.

**Comment by deepdwivedi** [comment]
HI Team, I am still facing the similar issue of not rendering bar chart , it works well with other charts.
![bar_chart_no_render](https://user-images.githubusercontent.com/7040610/76065225-34ecb680-5fb1-11ea-8844-69285e08061b.png)

**Comment by deepdwivedi** [comment]
Do we have any permanent fix for this.

**Comment by deepdwivedi** [comment]
{"error": "The datasource associated with this chart no longer exists", "stacktrace": "Traceback (most recent call last):\n  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/superset/views/core.py\", line 165, in check_datasource_perms\n    datasource_id, datasource_type, form_data\n  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/superset/views/utils.py\", line 171, in get_datasource_info\n    \"The datasource associated with this chart no longer exists\"\nsuperset.exceptions.SupersetException: The datasource associated with this chart no longer exists\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/superset/views/base.py\", line 120, in wraps\n    return f(self, *args, **kwargs)\n  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/superset/utils/decorators.py\", line 63, in wrapper\n    check_perms(*args, **kwargs)\n  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/superset/views/core.py\", line 168, in check_datasource_perms\n    raise SupersetSecurityException(str(e))\nsuperset.exceptions.SupersetSecurityException: The datasource associated with this chart no longer exists\n"}

**Comment by willbarrett** [comment]
Hi @deepdwivedi - from the error response you posted, it looks like the datasource that the chart reads from has been removed. Have you made any changes to your database connections or your datasource definitions recently? Changes in those areas could cause issues like the one you're experiencing here.
