### ISSUE TITLE
superset upgrade failed from v0.27 to v0.35

### ISSUE THREAD

**Issue by jsynl** [apache/incubator-superset#9204]
Hi :

I upgraded my software according to the manual, from v0.27 to v0.35. After upgrading, I found that the **Sources**  was not available, but the **Security** and **manage**  were OK. 
The error message as follows:

`ERROR: {"error": "Connection failed!\n\nThe error message returned was:\n(sqlite3.OperationalError) no such column: dbs.allow_run_sync [SQL: 'SELECT dbs.created_on AS dbs_created_on, dbs.changed_on AS dbs_changed_on, dbs.id AS dbs_id, dbs.verbose_name AS dbs_verbose_name, dbs.database_name AS dbs_database_name, dbs.sqlalchemy_uri AS dbs_sqlalchemy_uri, dbs.password AS dbs_password, dbs.cache_timeout AS dbs_cache_timeout, dbs.select_as_create_table_as AS dbs_select_as_create_table_as, dbs.expose_in_sqllab AS dbs_expose_in_sqllab, dbs.allow_run_sync AS dbs_allow_run_sync, dbs.allow_run_async AS dbs_allow_run_async, dbs.allow_ctas AS dbs_allow_ctas, dbs.allow_dml AS dbs_allow_dml, dbs.force_ctas_schema AS dbs_force_ctas_schema, dbs.allow_multi_schema_metadata_fetch AS dbs_allow_multi_schema_metadata_fetch, dbs.extra AS dbs_extra, dbs.perm AS dbs_perm, dbs.impersonate_user AS dbs_impersonate_user, dbs.created_by_fk AS dbs_created_by_fk, dbs.changed_by_fk AS dbs_changed_by_fk \\nFROM dbs \\nWHERE dbs.database_name = ?\\n LIMIT ? OFFSET ?'] [parameters: ('kylin', 1, 0)] (Background on this error at: http://sqlalche.me/e/e3q8)"}`

some body please help me，thanks！

#### Screenshots

![image](https://user-images.githubusercontent.com/38222663/75332227-012dd480-58bf-11ea-830c-f517fc8eaefe.png)

### Environment

- superset version: `0.35.2`
- python version: `3.6.4`
- flask version: `1.1.1`

**Comment by elukey** [comment]
Have you followed the procedure to upgrade the db schema?
https://superset.incubator.apache.org/installation.html#upgrading

**Comment by zhaoyongjie** [comment]
@jsynl 
This is a bug in kylinpy. I have fixed this problem. In kylinpy 2.4 and above fixed. you can run
```
 pip install -U kylinpy 
```
to upgrade

**Comment by jsynl** [comment]
@zhaoyongjie Hi zhaoyongjie, thank you for your help. This problem has been fixed. But I still have some troubles to ask you:

1. After repairing according to your suggestion, the following information(_**missing datasource permissions**_) will always appear when executing **superset init**:
```
2020-03-20 15:12:59,813:INFO:root:logging was configured successfully
2020-03-20 15:13:00,021:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
2020-03-20 15:13:02,454:INFO:root:Syncing role definition
2020-03-20 15:13:02,463:INFO:root:Syncing Admin perms
2020-03-20 15:13:02,597:INFO:root:Syncing Alpha perms
2020-03-20 15:13:02,734:INFO:root:Syncing Gamma perms
2020-03-20 15:13:02,870:INFO:root:Syncing granter perms
2020-03-20 15:13:03,004:INFO:root:Syncing sql_lab perms
2020-03-20 15:13:03,137:INFO:root:Fetching a set of all perms to lookup which ones are missing
2020-03-20 15:13:03,262:INFO:root:Creating missing datasource permissions.
2020-03-20 15:13:03,311:INFO:root:Creating missing database permissions.
2020-03-20 15:13:03,313:INFO:root:Creating missing metrics permissions
2020-03-20 15:13:03,342:INFO:root:Cleaning faulty perms
```

2. I thought it might be caused by other reasons, so I reinstalled it on another server computer according to the manual and found that the same problem still exists

3. The Superset can log in normally, but the database table cannot be added

Looking forward to your suggestion, thank you again

**Comment by zhaoyongjie** [comment]
@jsynl 
What database are you using? Superset will use SQLite as the database by default. If there is no special config, it will be saved in 

```
~ / .superset / superset.db
```

If you need to reinstall and there is no important data, you can try removing superset.db
